### PR TITLE
Adding option to show rendered image in full resolution.

### PR DESCRIPTION
**Pull request by h4n23s**
Allows users to view the last uploaded/rendered frame in their default image viewer.

grafik

### CODE REVIEW

**Comment by luguina** [comment]
Please use the code formating provided, we don't do import *

**Comment by h4n23s** [comment]
> Please use the code formating provided, we don't do import *

I will fix that.

> Re performance, have you tested the PR with very large frames (some rendered images are 50MB+ every now and then)

This depends heavily on how well your particular image viewer is optimized. Most modern ones already are (like windows and macs built-in ones). Others and especially older ones may take a while. The usage of sheepit requires a relatively modern PC anyway, so it's pretty safe to assume that most systems will be able to handle images with sizes greater than 50 megabytes.

**Comment by laurent-clouet** [comment]
Due to privacy concern, we don't want to display the full render output.
So, i can't accept that PR.

**Comment by h4n23s** [comment]
Personally, I can't understand why the user should not be able to see what was being rendered on his/her pc. If someone had malicious intentions they would always be able to modify the source code to keep every frame they rendered or even the whole blender project.

**Pull request closed without merging**
