### PR TITLE
Fix for OpenCL

### PR DESCRIPTION
**Pull request by fireplex**
Should allow proper ID detection for AMD cards.
May still cause issues for Vega cards between different Blender versions.

### CODE REVIEW

**Comment by intrigus** [comment]
Why are the special cases for the vega needed?

**Comment by fireplex** [comment]
> Why are the special cases for the vega needed?

Vega causes issues where the board name is different between Blender versions. To accommodate this it'd be necessary to change the board name depending on the Blender version.

**Comment by laurent-clouet** [comment]
Can you take care of the remark i made? so we can merge your code

**Comment by intrigus** [comment]
Do you know why the board name is different between blender versions.

**Comment by laurent-clouet** [comment]
I did some modification on your PR and i pushed it on 1451f4161d6632676b89b683ceb481db2f3e16c8
The python part should not be there (it's ok to not support 2.79 since it's less than 1/4 of projects)

**Comment by laurent-clouet** [comment]
It's on prod with 5.1684.3048.
Thanks again for the PR :)

**Pull request closed without merging**
