### PR TITLE
Dark mode theme

### PR DESCRIPTION
**Pull request by luguina**
Hi Laurent, I hope you are doing well. First of all, thank you for the idea and for keeping the Sheep It! service. 

I've been just a couple of weeks using Sheep It! but I love it and I'd like to help in several ways. I've seen that someone has been requesting a new feature (Dark mode) and I've spend some time this morning with the implementation. If you're OK, I'm planning to help as well with some other features and some ideas I have (happy to share with you first to ensure that we're aligned).

Long history short, here is the list of changes for the Dark mode implementation as [requested](https://www.sheepit-renderfarm.com/forum/viewtopic.php?f=11&t=394) by a user in the forum.

The pull request includes:
- light and dark modes on configuration screen
- light and dark modes on main (project screen)
- Sheep It! logo has been updated as well to support dark mode
- new CLI option -theme supporting 'light' and 'dark' options
- a new configuration element 'theme' has been added to the configuration file to persist between Sheep It! exAcutions

All the changes have been tested thoroughly but don't hesitate to ask or comment anything you might find.

This is a screenshot of configuration screens and job screen in dark mode:

SheepItDarkMode
JobRenderDarkMode

Thanks!
Luis

### CODE REVIEW

**Comment by laurent-clouet** [comment]
Thanks i'll look at it.

First impression: there is a lot of code formating / variable rename who are not related to the actual feature.

**Comment by luguina** [comment]
True Laurent. 
Reason being the code had a mix of CamelCase and underscore (Python-style) syntax so I took the opportunity to do some refactoring to improve future code readability and to comply with Java coding standards. If you're not keen with doing some code refactoring when a new feature is added then I'll avoid next time :D.
Let me know!

**Comment by laurent-clouet** [comment]
I don't mind refactoring/renaming but it should be a different PR.

**Comment by luguina** [comment]
OK, I'll take into account for the next time and will do in a separate PR.

**Comment by luguina** [comment]
Hi @laurent-clouet, don't want to bug you but any idea when you will take a look at this? I have a couple of extra improvements requested by customers but need this branch pulled in the main stream (as they touch some common modules). Thanks!

**Comment by laurent-clouet** [comment]
It will take some time since i need to separate the refactoring from the actual feature.

**Comment by laurent-clouet** [comment]
I'm testing the client and i look a bit strange.
I never use darkmode but on my linux the output a weird.

Is-it the indented output? 
Can you update your PR with a screenshot.


image

**Comment by luguina** [comment]
> It will take some time since i need to separate the refactoring from the actual feature.

You don't need to do it. I can easily do and submit two different PRs. Do you wan me to do it during the weekend?

**Comment by laurent-clouet** [comment]
Yes please.

**Comment by luguina** [comment]
> I'm testing the client and i look a bit strange.
> I never use darkmode but on my linux the output a weird.
> 
> Is-it the indented output?
> Can you update your PR with a screenshot.
> 
> image

You're right, it looks weird. I've updated the PR with the screenshots. Can you pls let me know the Linux version you have? Screenshots are captured on Ubuntu 19.10 with Gnome 3.34.2

**Comment by luguina** [comment]
> Yes please.

I'll then withdraw the PR in order to do it. Thanks!

**Comment by laurent-clouet** [comment]
It's ubuntu 18.10 and kde 5.50 (default from ubuntu)

**Comment by luguina** [comment]
> It's ubuntu 18.10 and kde 5.50 (default from ubuntu)

Perfect @laurent-clouet, I will test the build with KDE once I split the PR (in Windows and MacOS works fine).

**Pull request closed without merging**
