### PR TITLE
add the ability to set the priority of the render process as commandl…

### PR DESCRIPTION
**Pull request by principat**
…ine argument

### CODE REVIEW

**Comment by laurent-clouet** [comment]
Thanks for this pull request, it's the next one i'll merge.
There is few formatting issue but nothing i can't fix when i'll do the merge.

One question, why did you use the environment for the priority ? why not adding a parameter to the exec method?

**Comment by principat** [comment]
i used the env because it was also used for the number of cores. this was also add by env not by param.
There is no other reason

**Comment by laurent-clouet** [comment]
Merged on master with 11db5c4ea53924d9ad4e4f6cec659a8c2dd77ddb

Thanks again for the pull request!

As a todo, it will be nice to configure it from the swing ui.

**Comment by principat** [comment]
Ist at to-do list
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 05.01.17, 10:00, Laurent Clouet <notifications@github.com> schrieb:

  
    
      Merged on master with 11db5c4
    
    
      Thanks again for the pull request!
    
    
      As a todo, it will be nice to configure it from the swing ui.

**Pull request closed without merging**
