### PR TITLE
Possible untested fix for cuda issue #88

### PR DESCRIPTION
**Pull request by intrigus**

### CODE REVIEW

**Comment by intrigus** [comment]
This is a test build so you can test it, I unfortunately don't have any NVIDIA card...

[sheepit-client.jar.zip](https://github.com/laurent-clouet/sheepit-client/files/765144/sheepit-client.jar.zip)

**Comment by laurent-clouet** [comment]
Thanks for the try.
I do have one with 6GB and your patch does not work, i still have 4096MB detected.

**Comment by intrigus** [comment]
Hey @laurent-clouet could you please join http://webchat.freenode.net/?channels=#sheepit-farm ?
I'd like to talk about something dev related with you :)

**Comment by laurent-clouet** [comment]
Thanks for the good work!
Your fix is in master now!  673a4249003eced16966bcdbed75dfd48a249bc3

**Pull request closed without merging**
