### PR TITLE
Show compute method in user interface (CPU/GPU)

### PR DESCRIPTION
**Pull request by ekaj2**
This is in response to the feature request [here](https://github.com/laurent-clouet/sheepit-client/issues/119).

> It would be great if there'd be an indication in the client whether the current project is rendered on the CPU or GPU.

I added a compute method to the UI in the project info section.

sheepit_proj

### CODE REVIEW

**Comment by supersammy7000** [comment]
Shouldn't this be under the project section instead of the session? If you have gpu and cpu selected, which is the problem case this solves, the compute method can change from project to project still under the same session.

**Comment by ekaj2** [comment]
@supersammy7000 Sure, makes sense. I'll change it now.

**Comment by ekaj2** [comment]
@supersammy7000 That should fix it. I updated my original description as well.

**Comment by ekaj2** [comment]
Could someone do a check to make sure it switches correctly between GPU and CPU? I don't have a working GPU, and while I feel quite strongly that it *should* work, doesn't necessarily mean that it will.

**Comment by laurent-clouet** [comment]
I'll test it.
It don't really like all the commit in your branch but i'll cherry pick what i need :)
(i want the Intellij stuffs)

**Comment by ekaj2** [comment]
@laurent-clouet I had to remove a lot of that because it was wrong (e.g., assuming JavaFX instead of Swing). If you want a lot of that, I can go through and fix stuff like:

    if (boolVar == true)

To make it:

    if (boolVar)

IDEA is really good at stuff like that. What do you mean by "It don't really like all the commit in your branch"?

**Comment by laurent-clouet** [comment]
I mean there is a lot of "noise" on your pull request.
You want to create a new feature but you are also "cleaning up" stuffs who are not related.

It's ok, at the end i can merge it manually and separate the noise from the actual feature.

**Comment by ekaj2** [comment]
Alright, sorry to make more work. I'll try to keep my commits to the point next time :-)

**Comment by laurent-clouet** [comment]
I merged your feature into master with 8d3cf2d51eb047287bacade859554a3bd8203469
I did fix your code, the call for setComputeMethod was not at the right place, you were set the boolean after the call to setComputeMethod so it was always 'cpu'.

Thanks again for the pull request!

**Pull request closed without merging**
