### PR TITLE
Add GPL license.

### PR DESCRIPTION
**Pull request by supersammy7000**
I noticed in the FAQ the license was GPL but there was no GPL license in the repository.

### CODE REVIEW

**Comment by laurent-clouet** [comment]
Why not.
It's on every java file but yes it could be also added on root dir.

**Comment by laurent-clouet** [comment]
Actually no.
The gpl license of the project is gpl2 (as stated on the java files), your is gpl 3.

**Comment by supersammy7000** [comment]
Github recently added a feature that it shows on the top bar the license when it is in the root directory.

**Comment by supersammy7000** [comment]
It is on a lot of files but not every files. In the text it says "You should have received a copy of the GNU General Public License along with this program" I don't think one is included.

**Comment by laurent-clouet** [comment]
Thanks i added the license on java's header.
I also added a gpl2 file (under your name).

Thanks again for the pull request :)

**Comment by supersammy7000** [comment]
Thank you for being so responsive I did not expect you to respond after only 2 minutes.

**Pull request closed without merging**
