### PR TITLE
Fix #154 - Illegal Reflective Access

### LINKED ISSUE #154: Java 9: Illegal reflective access
This happened to Inspired2150 on his windows instance, but seems to be a wide-spread issue with java 9.

The relevant excerpt of the log (transcripted, so don't mind any typos)
```
Compute method: CPU
WARNING: An illegal reflective access operation has occured
WARNING: Illegal reflective access by com.ssheepit.client.os.windows.WinProcess (file://C:/Software/Sheepit/CPU/sheepit-client-5.606.2884.jar) to field java.lang.ProcessImpl.handle
WARNING: Please consider reporting this to the maintainers of com.sheepit.client.os.windows.WinProcess
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Frame rendered in 0min1s
```

Although this doesn't affect the client's functionality in any way, the last warning hints that this will be the case with future releases - perhaps even with java 10.

### PR DESCRIPTION
**Pull request by intrigus**
Use Process's pid() when it exists.
(Done via reflection so it also works for java versions < 9)
Else fall back to old reflective method.

### CODE REVIEW

**Comment by laurent-clouet** [comment]
Please check the code formator provided, your code doesn't follow it.
For example it should be
if (...) {
...
}
else {
...
}


try {
...
}
catch (...) {
...
}

**Comment by MCOfficer** [comment]
are you gonna work on this? i really want to see this being merged, so if you want, i can format the code correctly and PR that to your fork.

**Comment by intrigus** [comment]
This should be correct now, I guess.

**Comment by laurent-clouet** [comment]
Merge with 83af3d0a245e0018987bb304ab25cb5719682a1a
Thanks for the pull request! :)

**Pull request closed without merging**
