### PR TITLE
Custom Tile Size Implementation

### PR DESCRIPTION
**Pull request by JacksonML**
This should allow the rendering clients to select their own tile size. This is done in request to  #73 in which a request was made to add such a feature. If there's anything else that needs to be changed or that I forgot please let me know!

### CODE REVIEW

**Comment by laurent-clouet** [comment]
1- Why did you separated tileX and tileY ? it will be mostly the same number since the user doesn't know the size of the frame.
2- There is some formating issue, please check the formator i provided (i can be used with eclipse)

**Comment by JacksonML** [comment]
1. I separated them because that is how Blender allows people to choose. I can take away one of the tile sizes.
2. Alright. I'll download Eclipse (I've been using Netbeans) and try to reformat it.
3. Hmm... where are the config files stored? I was wanting to test but I could never find them.

**Comment by laurent-clouet** [comment]
3. check SettingsLoader class => System.getProperty("user.home") + File.separator + ".sheepit.conf"; 
on linux it's $HOME/.sheepit.conf

**Comment by laurent-clouet** [comment]
There is still a lot of formating issue but don't worry i'll fix them when i'll merge.
I'll do further testing and if everything is fine i'll merge it next week (or the next).

Thanks again for the pull request :)

**Comment by laurent-clouet** [comment]
I merged your code on master with 62f277ee010405372285dec8fe05b7bd30142100
As you can see i changed few things like remove the X on tile and FormatedTextField, code formating.


Thanks again for the pull request! :)

**Pull request closed without merging**
