### PR TITLE
create commandline cache-dir if not exist and add command based control to the text uis

### PR DESCRIPTION
**Pull request by principat**
if a cache_dir is given as command line argument and it does not exist it will try to create it with it parents

at the current implementation the argument was ignored if the directory does not exist

### CODE REVIEW

**Comment by laurent-clouet** [comment]
Thanks for the pull request!
It looks good, i'll test it and merge it in mid december (I'm travelling and i don't have a "coding pc")

**Comment by principat** [comment]
the second chang addresses #98 by typing block<ENTER> the current job will be blocked additional commands could be added

**Comment by laurent-clouet** [comment]
Please create separate pull request for different bugfix/feature so i can be review more easily.

**Comment by principat** [comment]
seams like i have to create a separate branch for each change/ fix to create a separate pull request

**Comment by supersammy7000** [comment]
A must have. Each change is something that should be considered. Git is based on using branches for changes to be merged into main branches. The reason this is done is so that you can merge in good changes and if there is something that needs to be changed you can change it while the good changes are already merged.

**Comment by principat** [comment]
I gonna close this and create new ones
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 26.11.16, 04:12, Lance <notifications@github.com> schrieb:

  
    
      A must have. Each change is something that should be considered. Git is based on using branches for changes to be merged into main branches. The reason this is done is so that you can merge in good changes and if there is something that needs to be changed you can change it while the good changes are already merged.

**Pull request closed without merging**
