### PR TITLE
Implemented flexible layout for swing

### LINKED ISSUE #25: Make field Name, Password and CPU cores slider a bit biger
Hey guys, just take a look at picture and see how it looks on Gnom, if u could fix it that would be great
sheepit

### PR DESCRIPTION
**Pull request by scribblemaniac**
The lack of progress on a flexible layout has been holding up pull requests #23 and #29, as well as just generally annoying me whenever I use the client, so I decided to do it myself.

The layout looks more or less the same as it did before, but it now adjusts based on the content and the size of the window. I have not been able to test how either GPU options or last rendered frame display affect the layout, however they *should* properly follow the layout.

Probably Closes #25

### CODE REVIEW

**Comment by laurent-clouet** [comment]
Sorry, I was too much busy on the server side to look at the client ui.
I tested and there is few things i don't really like 
* it's really big! Maybe there is too much marging 
* the black line under the logo
* alignment of GPU

Except that, I'm happy with it it's a really good start. 
I'll continue to test it this week on different platform, it's looking good for the integration.


screen02

screen03


To test the GPUs no need to have an actual device, simply add "devices.add(new GPUDevice("GeFore GT 780", 32433, "CUDA_4"));"  to GPU.java on line 101
It must work with 4 GPUs

**Comment by scribblemaniac** [comment]
1. Sorry for the large window size, it was for testing and I changed it back to the default size shortly after pulling, but you must've pulled it before I amended the commit.
2. I felt like there should've been some divider there but if you don't like it we can just remove the two calls to `labelImage.setBorder()`
3. That GPU alignment was not expected, it looks like it's aligning with the row above it. I'll see what I can do to correct that.

Thanks for the tip to add fake GPUs.

**Comment by scribblemaniac** [comment]
Okay, I've removed the line and fixed the gpu alignment. Just let me know if there is anything else that needs to be done for this.

Since you seem to like screenshots, here's one just for you:
4gpus

**Comment by laurent-clouet** [comment]
Thanks it's better now :)

**Comment by pierallard** [comment]
Nice job @scribblemaniac  :+1:

**Comment by laurent-clouet** [comment]
It's live! 
version 3.176.2276

**Comment by scribblemaniac** [comment]
@pierallard Thank you

@laurent-clouet Good to hear, thanks for the assistance

:smile:

**Pull request merged**
