### PR TITLE
Show how much credits earned in text and oneLine mode

### PR DESCRIPTION
**Pull request by timoschwarzer**

### CODE REVIEW

**Comment by not83** [comment]
Awesome!

**Comment by laurent-clouet** [comment]
Might getCreditEarnedOnCurrentSession fail so at either the exception should be silence or display a single line error on the oneLine ui.

Example:
---
BUILD SUCCESSFUL
Total time: 2 seconds
Server::getCreditEarnedOnCurrentSession exception java.net.MalformedURLException: no protocol: 
java.net.MalformedURLException: no protocol: 
        at java.net.URL.<init>(URL.java:585)
        at java.net.URL.<init>(URL.java:482)
        at java.net.URL.<init>(URL.java:431)
        at com.sheepit.client.Server.HTTPRequest(Server.java:470)
        at com.sheepit.client.Server.HTTPRequest(Server.java:464)
        at com.sheepit.client.Server.getCreditEarnedOnCurrentSession(Server.java:773)
        at com.sheepit.client.standalone.GuiTextOneLine.updateLine(GuiTextOneLine.java:73)
        at com.sheepit.client.standalone.GuiTextOneLine.status(GuiTextOneLine.java:38)
        at com.sheepit.client.Client.run(Client.java:109)
        at com.sheepit.client.standalone.GuiTextOneLine.start(GuiTextOneLine.java:26)
        at com.sheepit.client.standalone.Worker.doMain(Worker.java:291)
        at com.sheepit.client.standalone.Worker.main(Worker.java:92)
Frames rendered: 0 (0 Credits earned) remaining: 16 | Downloading project 
---

**Comment by timoschwarzer** [comment]
Will fix this in a few hours...

**Comment by not83** [comment]
Legend!

**Comment by timoschwarzer** [comment]
Fixed-

**Comment by laurent-clouet** [comment]
Thanks for the pull request!
I merged your change on commit d6a2254afcf2f6d660f87e8c95a70b4f365e5ff5

**Pull request closed without merging**
