### PR TITLE
Add support for FreeBSD in Client

### PR DESCRIPTION
**Pull request by harrim4n**
As Blender is available for FreeBSD (http://www.blender.org/download/), I decided to make the client compatible with FreeBSD. Obviously the server side will have to be modified as well, because right now the value "os=freebsd" will be rejected.

Also I am unable to verify if CUDA support works as is on FreeBSD because I do not have a CUDA compatible graphics card in the host that is running FreeBSD; maybe someone else can verify.

The current output when starting the .jar in this state is:
<code>
21-11 14:22:55 (debug) client version 3.3.2
Starting
</code>
<code>
21-11 14:22:55 (debug) GUI Starting
</code>
<code>
21-11 14:22:56 (debug) Server::getConfiguration url https://www.sheepit-renderfarm.com/server/config.php?login=****&password=*****&cpu_family=6&cpu_model=3c&cpu_model_name=Intel%28R%29+Xeon%28R%29+CPU+E3-1220+v3+%40+3.10GHz+%283092.90-MHz+K8-class+CPU%29&cpu_cores=4&os=freebsd&ram=16166608&bits=64bit&version=3.3.2&hostname=datatank&extras=
</code>
<code>
21-11 14:22:56 (debug) Server::HTTPRequest url(https://www.sheepit-renderfarm.com/server/config.php?login=******&password=******&cpu_family=6&cpu_model=3c&cpu_model_name=Intel%28R%29+Xeon%28R%29+CPU+E3-1220+v3+%40+3.10GHz+%283092.90-MHz+K8-class+CPU%29&cpu_cores=4&os=freebsd&ram=16166608&bits=64bit&version=3.3.2&hostname=datatank&extras=)
Requesting Job
</code>
<code>
21-11 14:22:56 (debug) GUI Requesting Job
</code>
<code>
21-11 14:22:56 (debug) Server::requestJob
</code>
<code>
21-11 14:22:56 (debug) Server::HTTPRequest url(https://www.sheepit-renderfarm.com/server/request_job.php?computemethod=1&cpu_cores=4)
</code>
<code>
21-11 14:22:57 (error) Server::requestJob: Utils.statusIsOK(document, 'jobrequest') -> ret JOB_REQUEST_ERROR_RENDERER_NOT_AVAILABLE
Error Client::renderingManagement exception requestJob (1) error requestJob: status is not ok (it's JOB_REQUEST_ERROR_RENDERER_NOT_AVAILABLE)
</code>
<code>
21-11 14:22:57 (error) Error Client::renderingManagement exception requestJob (1) error requestJob: status is not ok (it's JOB_REQUEST_ERROR_RENDERER_NOT_AVAILABLE)
</code>
<code>
21-11 14:22:57 (debug) Client::run exception com.sheepit.client.exception.FermeException: error requestJob: status is not ok (it's JOB_REQUEST_ERROR_RENDERER_NOT_AVAILABLE) stacktrace: com.sheepit.client.exception.FermeException: error requestJob: status is not ok (it's JOB_REQUEST_ERROR_RENDERER_NOT_AVAILABLE)
	at com.sheepit.client.Server.requestJob(Server.java:331)
	at com.sheepit.client.Client.run(Client.java:160)
	at com.sheepit.client.standalone.GuiText.start(GuiText.java:42)
	at com.sheepit.client.standalone.Worker.doMain(Worker.java:291)
	at com.sheepit.client.standalone.Worker.main(Worker.java:92)

### CODE REVIEW

**Comment by laurent-clouet** [comment]
Thanks for the modifications.
I'll install a freebsd to test your changes and to add the renderer on the server side.

You should also look at the coding style and indentation of the other files to match with your change.
For example we use tab for indentation.
(If you are using eclipse, there is a java formator provided.)

**Comment by laurent-clouet** [comment]
I tested your patch on a virtualbox machine, it does work :)
But why did you parse dmesg output, why you didn't used /proc (like linux) or sysctl (like mac) ?

**Comment by harrim4n** [comment]
That's good to hear.
I didn't use /proc, because the required files (cpuinfo, meminfo) don't exist on FreeBSD and I couldn't find any equivalent files.
As for sysctl, same issue. It does contain a few infos like
<code>
    hw.model: Intel(R) Xeon(R) CPU E3-1220 v3 @ 3.10GHz
</code>
<code>
    hw.realmem: 17196646400
</code>
but for example the CPU model and CPU family are not accessible via sysctl. I could of course only parse the missing infos from dmesg, but that would just be more work that necessary.

**Comment by laurent-clouet** [comment]
Thanks for the good work, I merged your code with the main branch. :)

The only difference is on the tabulation and removing of catch of java5 exception.

I also push a blender 2.76b 64bits freebsd archive on the main and demo website.
On linux, I put some librairies to reduce dependancy, i didn't do it for freebsd but i'll do it when i will learn a bit more about freebsd  (before today i never used bsd).


(The jar will go live this week

**Pull request closed without merging**
