### PR TITLE
Improve status messages

### PR DESCRIPTION
**Pull request by luguina**
Add three new status messages:
- Uploading frame, including rendered frame size.
- Stopping the client and;
- Disconnecting from SheepIt servers

to keep the user better informed about the actions performed by the client.

Additionally, amended some existing messages to make them more user friendly, while maintaining the existing technical logs.

Those changes are fully compatible with existing client and required for new UI.

### CODE REVIEW

**Comment by andylizi** [comment]
Without a state indicator, it's very confusing for new users to see the client seemly doing nothing for a long time when the connection is slow and the client is spending a long time uploading the frame. I think this PR is an overdue and much needed improvement. :grinning:

**Comment by laurent-clouet** [comment]
Please check your code formator because it looks different from mine. It's hard to see the actual changes.

**Comment by luguina** [comment]
That's strange as it's InteliJ. I'll check the autoformatting an will push again.

**Comment by laurent-clouet** [comment]
Thanks for the PR !

**Pull request merged**
