### PR TITLE
Adding the project name to the remaining time left to render

### PR DESCRIPTION
**Pull request by supersammy7000**
I just changed the current status of the rendering to include the project name.

### CODE REVIEW

**Comment by supersammy7000** [comment]
I added this because I think it is useful to know what project is rendering using the gui.

**Comment by laurent-clouet** [comment]
Thanks for the pull request but i will not merge it.
It's not the PR (or your) fault, it looks actually great but i'm working on a new ui for the client. Nothing revolutionary but it does include something similar to your changes.
You can checkout it out : https://github.com/laurent-clouet/sheepit-client/tree/new_ui it's not finished i have few remaining bugs.

Tell me what you think about it :)

**Comment by supersammy7000** [comment]
Sure thing. I will check that out when I get the chance.

**Comment by supersammy7000** [comment]
I just checked out the branch I think the gui is looking great. I think being able to check out those stats there will be really useful to see how the renderer has been going and I like the global and user stats. The text version has some bugs right now.

**Comment by laurent-clouet** [comment]
If you think of more stats, let me know. There is space for 1 or 2 more.

The text ui should be the same as before, what bug are your referring to ?

**Comment by supersammy7000** [comment]
I guess it is just one bug right now. After a frame and the time rendered is printed out it says

`Rendering project ""`
`Rendering`
`Rendering (remaining )`

**Comment by laurent-clouet** [comment]
Right thanks!

**Pull request closed without merging**
