### PR TITLE
Swing block settings

### PR DESCRIPTION
**Pull request by principat**
allow to set the maximum usage of memory and maximum render time for a project at the frontend. If a project needs more it will be blocked automated

it's based on my master combining all other pull requests. To create a separate branch for both based on the laurent-clouet:master would cost to much time to merge through the other branches. sorry!

### CODE REVIEW

**Comment by laurent-clouet** [comment]
You branch still have code formating issue, please fix them.
A code formator for eclipse you can use it.
(I'm also looking at how to add it to travis job.)

**Comment by principat** [comment]
How did you check this?
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 29.03.17, 12:42, Laurent Clouet <notifications@github.com> schrieb:
You branch still have code formating issue, please fix them.
A code formator for eclipse you can use it.
(I'm also looking at how to add it to travis job.)

**Comment by principat** [comment]
i have fixed the format issues except the server.java where it produce very long line.

**Comment by laurent-clouet** [comment]
I hope you don't mind, i took your idea of setting a limit on ram usage (and auto-block too) and did it the "right way" i.e. a way that the server can actually learn for the client.

On the master it's only for the swing ui, i'll most likely take your text/command line settings to finish it.
The same as last time, i'll make you an author of the feature or at least partially.

(If you want to talk directy i'm still on irc #sheepit-farm or discord at https://discord.io/blender )

**Comment by laurent-clouet** [comment]
I redid the "block on time" feature in a way the server can know why the process was kill and also knows the max time set by the client.

Thanks again for the idea of this feature.!

**Pull request closed without merging**
