### PR TITLE
Dump renderer log to working directory on error

### PR DESCRIPTION
**Pull request by AGSPhoenix**
When the renderer crashes, the log usually tells you what's wrong. However, you can't see that information without re-running the client with `--verbose`. If the issue is intermittent, or if you receive several long jobs in a row, it may take many hours before you find out what the issue is.

This change keeps the log in memory and tries to save it to disk in the event of an error, to make it easier to diagnose issues. While this does increase memory usage somewhat, my testing shows that a typical job's output doesn't amount to a significant amount of data, and I expect the StringBuilder's initial 64KB capacity should be sufficient for smaller jobs.

I'm not sure the implementation of this change has been done well. Java is not my preferred language, and I'm not very familiar with its standard library. If there are changes of any sort that you think should be made, let me know.

### CODE REVIEW

**Comment by AGSPhoenix** [comment]
What the fuck? This PR was like, one or two commits when I put it in. In fact, I think [this commit](https://github.com/laurent-clouet/sheepit-client/pull/53/commits/be94ca868d006a223872c7f71a069eea2ffd5e7d) was the entire thing. And I have 'Allow edits from maintainers' off, so how are all these other commits showing up?

Wonder if those force pushes Laurent did are causing some sort of git shenanigans.

**Comment by AGSPhoenix** [comment]
Oh god, every open PR is like this. #29, #96, #112

**Comment by zdanek** [comment]
@AGSPhoenix very strong reception of the situation here :D

**Comment by AGSPhoenix** [comment]
Imagine that you tweaked a thing to make it a bit better, put your changes in a little box, and put that box in a room at SheepIt HQ where people can look at it, discuss it, and start using it. You forget about it and go on with your life.

Three years later, you get a notification that your proposed change is ridiculously unwieldy and maybe there should be a guide to prevent idiots like you from doing this in the future (not the most generous interpretation of what you actually said, perhaps). Wondering what all the fuss is about with such a small change, you go back to that room and open the door, and out explodes 133 boxes containing everything from new labels and odd knickknacks to industrial sorting machines.

Needless to say, I was rather surprised by this.

**Pull request closed without merging**
