### PR TITLE
Added 'Hide to tray' option

### PR DESCRIPTION
**Pull request by Creator13**
This idea came from the roadmap on the website.
Added a button to hide the rendering window to the system tray. This will hide the window and add a tray icon:
trayicon

The window can be re-opened by double clicking the icon or by clicking 'Open'. There also is a shortcut to quit the program and to go to the settings panel directly.

P.S: For some reason, git wanted me to update the icons, while I couldn't find any real changes...

### CODE REVIEW

**Comment by laurent-clouet** [comment]
Thanks for the pull request!
It's looking good to me. I'm doing some test on different platforms, if everything went well, i'll merge the changes early next week.

**Comment by laurent-clouet** [comment]
I'm merged your changed with a7a8f5fa97ba7826a677ed13dbe89f5f2f9d9c7b
Thanks for the pull-request!

**Comment by scribblemaniac** [comment]
Good work, I'm sure Windows users will appreciate this :+1:

**Comment by laurent-clouet** [comment]
Linux and Mac too :)
It's supported in pretty much every window manager

**Comment by scribblemaniac** [comment]
Oh I did not know that, I'm going to have to try this out now :smile:

**Comment by Creator13** [comment]
Should work on Windows and Linux. The Java documentation doesn't mention Mac though..

**Comment by scribblemaniac** [comment]
I can confirm it works on Mac. It's not very pretty, but Java never was to begin with.

**Pull request closed without merging**
